version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
updates:
  - package-ecosystem: "GitHub Actions"
    directory: "/"
    schedule:
      interval: "weekly"
